name: Release CD

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --all-targets --release

    - name: List files
      run: ls -lisah ./target/release

    - name: Set up Hub
      run: |
        sudo snap install hub --classic

    - name: Deploy to Releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: 'hub release create
          -a ./target/release/bulkscale
          -m "$(git describe --tags --abbrev=0)"
          $(git describe --tags --abbrev=0)'